// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var EncUtf8 = require("crypto-js/enc-utf8");
var EncBase64 = require("crypto-js/enc-base64");

var partial_arg = EncUtf8;

function parseUtf(param) {
  return partial_arg.parse(param);
}

var partial_arg$1 = EncBase64;

function parseB64(param) {
  return partial_arg$1.parse(param);
}

var partial_arg$2 = EncUtf8;

function toUtf(param) {
  return partial_arg$2.stringify(param);
}

var partial_arg$3 = EncBase64;

function toB64(param) {
  return partial_arg$3.stringify(param);
}

function concat(param, param$1) {
  return List.fold_left((function (prim, prim$1) {
                return prim.concat(prim$1);
              }), param, param$1);
}

var one = parseUtf("Hello world");

var two = parseUtf("Hi back");

var three = parseB64("eVrXh3hgaLDmf7ZUz2ntxCdZ");

var both = concat(one, /* :: */[
      two,
      /* :: */[
        three,
        /* [] */0
      ]
    ]);

console.log(toB64(both));

exports.parseUtf = parseUtf;
exports.parseB64 = parseB64;
exports.toUtf = toUtf;
exports.toB64 = toB64;
exports.concat = concat;
exports.one = one;
exports.two = two;
exports.three = three;
exports.both = both;
/* partial_arg Not a pure module */
