// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var CryptoJsException = Caml_exceptions.create("CryptoJs.CryptoJsException");

exports.CryptoJsException = CryptoJsException;
/* No side effect */
