// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Sha1 = require("crypto-js/sha1");
var Sha3 = require("crypto-js/sha3");
var EncLatin1 = require("crypto-js/enc-latin1");

var hash = Sha1("This is my string");

console.log(hash.toString());

console.log(EncLatin1.stringify(hash));

var hmacHash = Sha3("whoa dude");

console.log(hmacHash.toString());

exports.hash = hash;
exports.hmacHash = hmacHash;
/* hash Not a pure module */
